version: '3.8'

services:
  multimodal-ai:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./assets:/app/assets
      - ./vector_db:/app/vector_db
    restart: unless-stopped
    
  # Optional: Add Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped